rocketmq:
  name-server: 192.168.152.138:9876
  # 生产者配置
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: test_group
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2

spring:
  rabbitmq:
    host: 192.168.3.23
    port: 5672
    username: admin
    password: admin
    virtual-host: /