spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.152.136:3306/test
    username: xxzou
    password: 123456
  jpa:
    show-sql: true


mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml
