spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.23:3306/test
    username: xxzou
    password: 123456
  jpa:
    show-sql: true


datasource:
  a:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.152.130:3306/data_source1
    username: xxzou
    password: Abc1234567890!
  b:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.152.130:3306/data_source2
    username: xxzou
    password: Abc1234567890!



mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml
